require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompletedChallengesController do

  # This should return the minimal set of attributes required to create a valid
  # CompletedChallenge. As you add validations to CompletedChallenge, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all completed_challenges as @completed_challenges" do
      completed_challenge = CompletedChallenge.create! valid_attributes
      get :index
      assigns(:completed_challenges).should eq([completed_challenge])
    end
  end

  describe "GET show" do
    it "assigns the requested completed_challenge as @completed_challenge" do
      completed_challenge = CompletedChallenge.create! valid_attributes
      get :show, :id => completed_challenge.id.to_s
      assigns(:completed_challenge).should eq(completed_challenge)
    end
  end

  describe "GET new" do
    it "assigns a new completed_challenge as @completed_challenge" do
      get :new
      assigns(:completed_challenge).should be_a_new(CompletedChallenge)
    end
  end

  describe "GET edit" do
    it "assigns the requested completed_challenge as @completed_challenge" do
      completed_challenge = CompletedChallenge.create! valid_attributes
      get :edit, :id => completed_challenge.id.to_s
      assigns(:completed_challenge).should eq(completed_challenge)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CompletedChallenge" do
        expect {
          post :create, :completed_challenge => valid_attributes
        }.to change(CompletedChallenge, :count).by(1)
      end

      it "assigns a newly created completed_challenge as @completed_challenge" do
        post :create, :completed_challenge => valid_attributes
        assigns(:completed_challenge).should be_a(CompletedChallenge)
        assigns(:completed_challenge).should be_persisted
      end

      it "redirects to the created completed_challenge" do
        post :create, :completed_challenge => valid_attributes
        response.should redirect_to(CompletedChallenge.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved completed_challenge as @completed_challenge" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedChallenge.any_instance.stub(:save).and_return(false)
        post :create, :completed_challenge => {}
        assigns(:completed_challenge).should be_a_new(CompletedChallenge)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedChallenge.any_instance.stub(:save).and_return(false)
        post :create, :completed_challenge => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested completed_challenge" do
        completed_challenge = CompletedChallenge.create! valid_attributes
        # Assuming there are no other completed_challenges in the database, this
        # specifies that the CompletedChallenge created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CompletedChallenge.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => completed_challenge.id, :completed_challenge => {'these' => 'params'}
      end

      it "assigns the requested completed_challenge as @completed_challenge" do
        completed_challenge = CompletedChallenge.create! valid_attributes
        put :update, :id => completed_challenge.id, :completed_challenge => valid_attributes
        assigns(:completed_challenge).should eq(completed_challenge)
      end

      it "redirects to the completed_challenge" do
        completed_challenge = CompletedChallenge.create! valid_attributes
        put :update, :id => completed_challenge.id, :completed_challenge => valid_attributes
        response.should redirect_to(completed_challenge)
      end
    end

    describe "with invalid params" do
      it "assigns the completed_challenge as @completed_challenge" do
        completed_challenge = CompletedChallenge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedChallenge.any_instance.stub(:save).and_return(false)
        put :update, :id => completed_challenge.id.to_s, :completed_challenge => {}
        assigns(:completed_challenge).should eq(completed_challenge)
      end

      it "re-renders the 'edit' template" do
        completed_challenge = CompletedChallenge.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompletedChallenge.any_instance.stub(:save).and_return(false)
        put :update, :id => completed_challenge.id.to_s, :completed_challenge => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested completed_challenge" do
      completed_challenge = CompletedChallenge.create! valid_attributes
      expect {
        delete :destroy, :id => completed_challenge.id.to_s
      }.to change(CompletedChallenge, :count).by(-1)
    end

    it "redirects to the completed_challenges list" do
      completed_challenge = CompletedChallenge.create! valid_attributes
      delete :destroy, :id => completed_challenge.id.to_s
      response.should redirect_to(completed_challenges_url)
    end
  end

end
