require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GameplansController do

  # This should return the minimal set of attributes required to create a valid
  # Gameplan. As you add validations to Gameplan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all gameplans as @gameplans" do
      gameplan = Gameplan.create! valid_attributes
      get :index
      assigns(:gameplans).should eq([gameplan])
    end
  end

  describe "GET show" do
    it "assigns the requested gameplan as @gameplan" do
      gameplan = Gameplan.create! valid_attributes
      get :show, :id => gameplan.id.to_s
      assigns(:gameplan).should eq(gameplan)
    end
  end

  describe "GET new" do
    it "assigns a new gameplan as @gameplan" do
      get :new
      assigns(:gameplan).should be_a_new(Gameplan)
    end
  end

  describe "GET edit" do
    it "assigns the requested gameplan as @gameplan" do
      gameplan = Gameplan.create! valid_attributes
      get :edit, :id => gameplan.id.to_s
      assigns(:gameplan).should eq(gameplan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gameplan" do
        expect {
          post :create, :gameplan => valid_attributes
        }.to change(Gameplan, :count).by(1)
      end

      it "assigns a newly created gameplan as @gameplan" do
        post :create, :gameplan => valid_attributes
        assigns(:gameplan).should be_a(Gameplan)
        assigns(:gameplan).should be_persisted
      end

      it "redirects to the created gameplan" do
        post :create, :gameplan => valid_attributes
        response.should redirect_to(Gameplan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gameplan as @gameplan" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gameplan.any_instance.stub(:save).and_return(false)
        post :create, :gameplan => {}
        assigns(:gameplan).should be_a_new(Gameplan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gameplan.any_instance.stub(:save).and_return(false)
        post :create, :gameplan => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gameplan" do
        gameplan = Gameplan.create! valid_attributes
        # Assuming there are no other gameplans in the database, this
        # specifies that the Gameplan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gameplan.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => gameplan.id, :gameplan => {'these' => 'params'}
      end

      it "assigns the requested gameplan as @gameplan" do
        gameplan = Gameplan.create! valid_attributes
        put :update, :id => gameplan.id, :gameplan => valid_attributes
        assigns(:gameplan).should eq(gameplan)
      end

      it "redirects to the gameplan" do
        gameplan = Gameplan.create! valid_attributes
        put :update, :id => gameplan.id, :gameplan => valid_attributes
        response.should redirect_to(gameplan)
      end
    end

    describe "with invalid params" do
      it "assigns the gameplan as @gameplan" do
        gameplan = Gameplan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gameplan.any_instance.stub(:save).and_return(false)
        put :update, :id => gameplan.id.to_s, :gameplan => {}
        assigns(:gameplan).should eq(gameplan)
      end

      it "re-renders the 'edit' template" do
        gameplan = Gameplan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gameplan.any_instance.stub(:save).and_return(false)
        put :update, :id => gameplan.id.to_s, :gameplan => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gameplan" do
      gameplan = Gameplan.create! valid_attributes
      expect {
        delete :destroy, :id => gameplan.id.to_s
      }.to change(Gameplan, :count).by(-1)
    end

    it "redirects to the gameplans list" do
      gameplan = Gameplan.create! valid_attributes
      delete :destroy, :id => gameplan.id.to_s
      response.should redirect_to(gameplans_url)
    end
  end

end
