require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrganisationsController do

  # This should return the minimal set of attributes required to create a valid
  # Organisation. As you add validations to Organisation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all organisations as @organisations" do
      organisation = Organisation.create! valid_attributes
      get :index
      assigns(:organisations).should eq([organisation])
    end
  end

  describe "GET show" do
    it "assigns the requested organisation as @organisation" do
      organisation = Organisation.create! valid_attributes
      get :show, :id => organisation.id.to_s
      assigns(:organisation).should eq(organisation)
    end
  end

  describe "GET new" do
    it "assigns a new organisation as @organisation" do
      get :new
      assigns(:organisation).should be_a_new(Organisation)
    end
  end

  describe "GET edit" do
    it "assigns the requested organisation as @organisation" do
      organisation = Organisation.create! valid_attributes
      get :edit, :id => organisation.id.to_s
      assigns(:organisation).should eq(organisation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Organisation" do
        expect {
          post :create, :organisation => valid_attributes
        }.to change(Organisation, :count).by(1)
      end

      it "assigns a newly created organisation as @organisation" do
        post :create, :organisation => valid_attributes
        assigns(:organisation).should be_a(Organisation)
        assigns(:organisation).should be_persisted
      end

      it "redirects to the created organisation" do
        post :create, :organisation => valid_attributes
        response.should redirect_to(Organisation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved organisation as @organisation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Organisation.any_instance.stub(:save).and_return(false)
        post :create, :organisation => {}
        assigns(:organisation).should be_a_new(Organisation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Organisation.any_instance.stub(:save).and_return(false)
        post :create, :organisation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested organisation" do
        organisation = Organisation.create! valid_attributes
        # Assuming there are no other organisations in the database, this
        # specifies that the Organisation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Organisation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => organisation.id, :organisation => {'these' => 'params'}
      end

      it "assigns the requested organisation as @organisation" do
        organisation = Organisation.create! valid_attributes
        put :update, :id => organisation.id, :organisation => valid_attributes
        assigns(:organisation).should eq(organisation)
      end

      it "redirects to the organisation" do
        organisation = Organisation.create! valid_attributes
        put :update, :id => organisation.id, :organisation => valid_attributes
        response.should redirect_to(organisation)
      end
    end

    describe "with invalid params" do
      it "assigns the organisation as @organisation" do
        organisation = Organisation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Organisation.any_instance.stub(:save).and_return(false)
        put :update, :id => organisation.id.to_s, :organisation => {}
        assigns(:organisation).should eq(organisation)
      end

      it "re-renders the 'edit' template" do
        organisation = Organisation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Organisation.any_instance.stub(:save).and_return(false)
        put :update, :id => organisation.id.to_s, :organisation => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested organisation" do
      organisation = Organisation.create! valid_attributes
      expect {
        delete :destroy, :id => organisation.id.to_s
      }.to change(Organisation, :count).by(-1)
    end

    it "redirects to the organisations list" do
      organisation = Organisation.create! valid_attributes
      delete :destroy, :id => organisation.id.to_s
      response.should redirect_to(organisations_url)
    end
  end

end
