require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserSpecificGameplansController do

  # This should return the minimal set of attributes required to create a valid
  # UserSpecificGameplan. As you add validations to UserSpecificGameplan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all user_specific_gameplans as @user_specific_gameplans" do
      user_specific_gameplan = UserSpecificGameplan.create! valid_attributes
      get :index
      assigns(:user_specific_gameplans).should eq([user_specific_gameplan])
    end
  end

  describe "GET show" do
    it "assigns the requested user_specific_gameplan as @user_specific_gameplan" do
      user_specific_gameplan = UserSpecificGameplan.create! valid_attributes
      get :show, :id => user_specific_gameplan.id.to_s
      assigns(:user_specific_gameplan).should eq(user_specific_gameplan)
    end
  end

  describe "GET new" do
    it "assigns a new user_specific_gameplan as @user_specific_gameplan" do
      get :new
      assigns(:user_specific_gameplan).should be_a_new(UserSpecificGameplan)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_specific_gameplan as @user_specific_gameplan" do
      user_specific_gameplan = UserSpecificGameplan.create! valid_attributes
      get :edit, :id => user_specific_gameplan.id.to_s
      assigns(:user_specific_gameplan).should eq(user_specific_gameplan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserSpecificGameplan" do
        expect {
          post :create, :user_specific_gameplan => valid_attributes
        }.to change(UserSpecificGameplan, :count).by(1)
      end

      it "assigns a newly created user_specific_gameplan as @user_specific_gameplan" do
        post :create, :user_specific_gameplan => valid_attributes
        assigns(:user_specific_gameplan).should be_a(UserSpecificGameplan)
        assigns(:user_specific_gameplan).should be_persisted
      end

      it "redirects to the created user_specific_gameplan" do
        post :create, :user_specific_gameplan => valid_attributes
        response.should redirect_to(UserSpecificGameplan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_specific_gameplan as @user_specific_gameplan" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserSpecificGameplan.any_instance.stub(:save).and_return(false)
        post :create, :user_specific_gameplan => {}
        assigns(:user_specific_gameplan).should be_a_new(UserSpecificGameplan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserSpecificGameplan.any_instance.stub(:save).and_return(false)
        post :create, :user_specific_gameplan => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_specific_gameplan" do
        user_specific_gameplan = UserSpecificGameplan.create! valid_attributes
        # Assuming there are no other user_specific_gameplans in the database, this
        # specifies that the UserSpecificGameplan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UserSpecificGameplan.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => user_specific_gameplan.id, :user_specific_gameplan => {'these' => 'params'}
      end

      it "assigns the requested user_specific_gameplan as @user_specific_gameplan" do
        user_specific_gameplan = UserSpecificGameplan.create! valid_attributes
        put :update, :id => user_specific_gameplan.id, :user_specific_gameplan => valid_attributes
        assigns(:user_specific_gameplan).should eq(user_specific_gameplan)
      end

      it "redirects to the user_specific_gameplan" do
        user_specific_gameplan = UserSpecificGameplan.create! valid_attributes
        put :update, :id => user_specific_gameplan.id, :user_specific_gameplan => valid_attributes
        response.should redirect_to(user_specific_gameplan)
      end
    end

    describe "with invalid params" do
      it "assigns the user_specific_gameplan as @user_specific_gameplan" do
        user_specific_gameplan = UserSpecificGameplan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserSpecificGameplan.any_instance.stub(:save).and_return(false)
        put :update, :id => user_specific_gameplan.id.to_s, :user_specific_gameplan => {}
        assigns(:user_specific_gameplan).should eq(user_specific_gameplan)
      end

      it "re-renders the 'edit' template" do
        user_specific_gameplan = UserSpecificGameplan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserSpecificGameplan.any_instance.stub(:save).and_return(false)
        put :update, :id => user_specific_gameplan.id.to_s, :user_specific_gameplan => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_specific_gameplan" do
      user_specific_gameplan = UserSpecificGameplan.create! valid_attributes
      expect {
        delete :destroy, :id => user_specific_gameplan.id.to_s
      }.to change(UserSpecificGameplan, :count).by(-1)
    end

    it "redirects to the user_specific_gameplans list" do
      user_specific_gameplan = UserSpecificGameplan.create! valid_attributes
      delete :destroy, :id => user_specific_gameplan.id.to_s
      response.should redirect_to(user_specific_gameplans_url)
    end
  end

end
